In [1]:
!pip install sentence_transformers
%pip install pyarrow
%pip install --use-pep517 annoy
%pip install tensorflow
%pip install pydot

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.11/site-packages (2.2.2)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (4.30.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (4.67.3)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (2.11.0)
Requirement already satisfied: torchvision in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (0.26.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (2.4.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (1.8.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (1.17.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (3.9.4)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (0.2.1)
Requirement already satisfied: huggingface-hub>=0.4.0 in /usr/local/lib/python3.11/site-packages (from sentence_transformers) (0.16.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/site-packages (from huggingface-hub>=0.4.0->sentence_transformers) (3.25.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/site-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2026.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2.33.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/site-packages (from huggingface-hub>=0.4.0->sentence_transformers) (6.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/site-packages (from huggingface-hub>=0.4.0->sentence_transformers) (4.15.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/site-packages (from huggingface-hub>=0.4.0->sentence_transformers) (26.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (79.0.1)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence_transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence_transformers) (13.0.85)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/site-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (2026.4.4)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.11/site-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/site-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (0.7.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/site-packages (from nltk->sentence_transformers) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/site-packages (from nltk->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.11/site-packages (from torchvision->sentence_transformers) (12.2.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch>=1.6.0->sentence_transformers) (1.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=1.6.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/site-packages (from jinja2->torch>=1.6.0->sentence_transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.11/site-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.11/site-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2026.2.25)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pyarrow in /usr/local/lib/python3.11/site-packages (23.0.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: annoy in /usr/local/lib/python3.11/site-packages (1.17.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /usr/local/lib/python3.11/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.11/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.11/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/site-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /usr/local/lib/python3.11/site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (2.33.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/site-packages (from tensorflow) (79.0.1)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.11/site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (2.4.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in /usr/local/lib/python3.11/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/site-packages (from keras>=3.12.0->tensorflow) (14.3.3)
Requirement already satisfied: namex in /usr/local/lib/python3.11/site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pydot in /usr/local/lib/python3.11/site-packages (4.0.1)
Requirement already satisfied: pyparsing>=3.1.0 in /usr/local/lib/python3.11/site-packages (from pydot) (3.3.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install pandas

%pip uninstall -y sentence-transformers transformers huggingface_hub
%pip install sentence-transformers==2.2.2 transformers==4.30.2 huggingface_hub==0.16.4

Requirement already satisfied: pandas in /usr/local/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Found existing installation: sentence-transformers 2.2.2
Uninstalling sentence-transformers-2.2.2:
  Successfully uninstalled sentence-transformers-2.2.2
Found existing installation: transformers 4.30.2
Uninstalling transformers-4.30.2:
  Successfully uninstalled transformers-4.30.2
Found existing installation: huggingface-hub 0.16.4
Uninstalling huggingface-hub-0.16.4:
  Successfully uninstalled huggingface-hub-0.16.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.
Collecting sentence-transformers==2.2.2
  Using cached sentence_transformers-2.2.2-py3-none-any.whl
Collecting transformers==4.30.2
  Using cached transformers-4.30.2-py3-none-any.whl.metadata (113 kB)
Collecting huggingface_hub==0.16.4
  Using cached huggingface_hub-0.16.4-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (4.67.3)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (2.11.0)
Requirement already satisfied: torchvision in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (0.26.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (2.4.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (1.8.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (1.17.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (3.9.4)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/site-packages (from sentence-transformers==2.2.2) (0.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/site-packages (from transformers==4.30.2) (3.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/site-packages (from transformers==4.30.2) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/site-packages (from transformers==4.30.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/site-packages (from transformers==4.30.2) (2026.4.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (from transformers==4.30.2) (2.33.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.11/site-packages (from transformers==4.30.2) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/site-packages (from transformers==4.30.2) (0.7.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/site-packages (from huggingface_hub==0.16.4) (2026.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/site-packages (from huggingface_hub==0.16.4) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (79.0.1)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.11/site-packages (from torch>=1.6.0->sentence-transformers==2.2.2) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.11/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.6.0->sentence-transformers==2.2.2) (13.0.85)
Requirement already satisfied: click in /usr/local/lib/python3.11/site-packages (from nltk->sentence-transformers==2.2.2) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/site-packages (from nltk->sentence-transformers==2.2.2) (1.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests->transformers==4.30.2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests->transformers==4.30.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.11/site-packages (from requests->transformers==4.30.2) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.11/site-packages (from requests->transformers==4.30.2) (2026.2.25)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn->sentence-transformers==2.2.2) (3.6.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.11/site-packages (from torchvision->sentence-transformers==2.2.2) (12.2.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch>=1.6.0->sentence-transformers==2.2.2) (1.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=1.6.0->sentence-transformers==2.2.2) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/site-packages (from jinja2->torch>=1.6.0->sentence-transformers==2.2.2) (3.0.3)
Using cached transformers-4.30.2-py3-none-any.whl (7.2 MB)
Using cached huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
Installing collected packages: huggingface_hub, transformers, sentence-transformers
Successfully installed huggingface_hub-0.16.4 sentence-transformers-2.2.2 transformers-4.30.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import gc
from annoy import AnnoyIndex
import pandas as pd
import glob
import numpy as np
from sentence_transformers import SentenceTransformer, util
import pandas as pd

for root, dirs, files in os.walk("."):
    for name in files:
        print(os.path.join(root, name))

./query_7.csv
./product_113.csv
./product_107.csv
./product_82.csv
./product_96.csv
./product_41.csv
./product_55.csv
./product_69.csv
./product_68.csv
./product_54.csv
./product_40.csv
./product_97.csv
./product_83.csv
./product_106.csv
./product_112.csv
./query_6.csv
./query_4.csv
./product_104.csv
./product_110.csv
./product_138.csv
./product_95.csv
./product_81.csv
./product_56.csv
./product_42.csv
./product_43.csv
./product_57.csv
./product_80.csv
./product_94.csv
./product_139.csv
./product_111.csv
./product_105.csv
./Cleaning.ipynb
./query_5.csv
./query_1.csv
./product_129.csv
./product_101.csv
./product_115.csv
./product_90.csv
./product_84.csv
./product_53.csv
./product_47.csv
./product_46.csv
./product_52.csv
./product_85.csv
./product_91.csv
./query_model.tflite
./product_114.csv
./product_100.csv
./product_128.csv
./query_2.csv
./product_116.csv
./product_102.csv
./product_87.csv
./product_93.csv
./product_78.csv
./product_44.csv
./product_50.csv
./product_51.csv
./product_45.csv
./product_79.csv
./query_model.tree
./product_92.csv
./product_86.csv
./product_103.csv
./product_117.csv
./query_3.csv
./query_26.csv
./training.ipynb
./product_22.csv
./product_36.csv
./product_37.csv
./product_23.csv
./query_27.csv
./query_19.csv
./query_25.csv
./product_9.csv
./neighbors.csv
./product_35.csv
./product_21.csv
./product_20.csv
./product_34.csv
./product_8.csv
./query_24.csv
./query_18.csv
./query_20.csv
./product_18.csv
./product_30.csv
./product_24.csv
./product_25.csv
./product_31.csv
./product_19.csv
./query_embeddings.csv
./query_21.csv
./query_23.csv
./product_embeddings.csv
./training copy.ipynb
./product_27.csv
./product_33.csv
./product_32.csv
./product_26.csv
./Cleaning-Copy1.ipynb
./query_22.csv
./query_13.csv
./product_3.csv
./product_17.csv
./product_16.csv
./product_2.csv
./query_12.csv
./query_10.csv
./query_model_output.tflite
./product_14.csv
./df_results_full.csv
./product_28.csv
./product_29.csv
./product_15.csv
./product_1.csv
./dataset_mini.csv
./query_11.csv
./query_15.csv
./query_29.csv
./product_ids.csv
./product_5.csv
./product_39.csv
./product_11.csv
./product_10.csv
./product_38.csv
./product_4.csv
./query_28.csv
./query_14.csv
./query_16.csv
./product_6.csv
./product_140.csv
./product_12.csv
./product_13.csv
./product_7.csv
./query_17.csv
./Convert.ipynb
./product_132.csv
./product_126.csv
./product_60.csv
./product_74.csv
./product_48.csv
./product_49.csv
./product_75.csv
./product_61.csv
./product_127.csv
./product_133.csv
./query.tree
./product_125.csv
./product_131.csv
./product_119.csv
./product_88.csv
./product_77.csv
./product_63.csv
./product_62.csv
./product_76.csv
./product_89.csv
./product_118.csv
./product_130.csv
./product_124.csv
./query_8.csv
./product_108.csv
./product_120.csv
./product_134.csv
./product_99.csv
./product_72.csv
./product_66.csv
./product_67.csv
./product_73.csv
./product_98.csv
./df_query_test_top50.csv
./product_135.csv
./product_121.csv
./product_109.csv
./query_9.csv
./product_137.csv
./product_123.csv
./product_59.csv
./product_65.csv
./product_71.csv
./product_70.csv
./product_64.csv
./product_58.csv
./product_122.csv
./product_136.csv
./models/all-MiniLM-L6-v2-quant.tflite
./models/tokenizers/all-MiniLM-L6-v2_tokenizer.json
./saved_models/latest.keras
./saved_models/best_model4 copy.keras
./saved_models/best_model4.h5
./.ipynb_checkpoints/Cleaning-checkpoint.ipynb
./.ipynb_checkpoints/training copy-checkpoint.ipynb
./.ipynb_checkpoints/Convert-checkpoint.ipynb
./.ipynb_checkpoints/training-checkpoint.ipynb
./.ipynb_checkpoints/Cleaning-Copy1-checkpoint.ipynb

In [3]:
df_queries_table = pd.read_parquet('../shopping_queries_dataset/shopping_queries_dataset_examples.parquet')
df_reduced_queries_table = df_queries_table[df_queries_table["small_version"] == 1]

df_products_table = pd.read_parquet('../shopping_queries_dataset/shopping_queries_dataset_products.parquet')
df_metaData_table = pd.read_csv("../shopping_queries_dataset/shopping_queries_dataset_sources.csv")

df_reduced_queries_table = df_reduced_queries_table[df_queries_table["product_locale"] == "us"]
df_reduced_queries_table = df_reduced_queries_table[(df_reduced_queries_table.esci_label == 'E') | (df_reduced_queries_table.esci_label == 'I')]

/tmp/ipykernel_808/4058875514.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_reduced_queries_table = df_reduced_queries_table[df_queries_table["product_locale"] == "us"]

In [4]:
df_joined = pd.merge(
    df_reduced_queries_table.head(),
    df_products_table,
    how="left",
    on=["product_id", "product_id"]
)

In [5]:
df_joined.head()

,example_id,query,query_id,product_id,product_locale_x,esci_label,small_version,large_version,split,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale_y
0,16,!awnmower tires without rims,1,B075SCHMPY,us,I,1,1,train,"RamPro 10"" All Purpose Utility Air Tires/Wheel...","<b>About The Ram-Pro All Purpose Utility 10"" A...",✓ The Ram-Pro Ten Inch ready to install Air Ti...,RamPro,10 Inch,us
1,17,!awnmower tires without rims,1,B08L3B9B9P,us,E,1,1,train,MaxAuto 2-Pack 13x5.00-6 2PLY Turf Mower Tract...,MaxAuto 2-Pack 13x5.00-6 2PLY Turf Mower Tract...,Please check your existing tire Sidewall for t...,MaxAuto,NaN,us
2,18,!awnmower tires without rims,1,B082K7V2GZ,us,I,1,1,train,NEIKO 20601A 14.5 inch Steel Tire Spoon Lever ...,NaN,[QUALITY]: Hardened Steel-Iron construction wi...,Neiko,NaN,us
3,20,!awnmower tires without rims,1,B07C1WZG12,us,E,1,1,train,(Set of 2) 15x6.00-6 Husqvarna/Poulan Tire Whe...,No fuss. Just take off your old assembly and r...,Tire size:15x6.00-6 Ply: 4 Tubeless\n6x4.5 Whe...,Antego Tire & Wheel,Husqvarna Silver,us
4,21,!awnmower tires without rims,1,B077QMNXTS,us,E,1,1,train,MaxAuto 2 Pcs 16x6.50-8 Lawn Mower Tire for Ga...,<br>Tire Specifications:<br> 1. Material: Rubb...,"Set of 2 16X6.50-8, 16x6.50x8, 16-6.50-8 Lawn ...",MaxAuto,Black,us

In [7]:
def find_embeddings(lst_product_title,i, maxlen):
    # Define a list of sentences
    sentences = list(lst_product_title)[i:i+step]
    sentence_embeddings = model.encode(sentences, convert_to_tensor=True)

    return np.array(sentence_embeddings)

In [8]:
# Load a pre-trained model (you can choose from various models like BERT, RoBERTa, etc.)
model = SentenceTransformer('all-MiniLM-L6-v2')

Downloading .gitattributes: 0.00B [00:00, ?B/s]

Downloading config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading README.md: 0.00B [00:00, ?B/s]

Downloading config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading (…)ce_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading data_config.json: 0.00B [00:00, ?B/s]

Downloading model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading model.onnx:   0%|          | 0.00/90.4M [00:00<?, ?B/s]

Downloading model_O1.onnx:   0%|          | 0.00/90.4M [00:00<?, ?B/s]

Downloading model_O2.onnx:   0%|          | 0.00/90.3M [00:00<?, ?B/s]

Downloading model_O3.onnx:   0%|          | 0.00/90.3M [00:00<?, ?B/s]

Downloading model_O4.onnx:   0%|          | 0.00/45.2M [00:00<?, ?B/s]

Downloading model_qint8_arm64.onnx:   0%|          | 0.00/23.0M [00:00<?, ?B/s]

Downloading (…)el_qint8_avx512.onnx:   0%|          | 0.00/23.0M [00:00<?, ?B/s]

Downloading (…)nt8_avx512_vnni.onnx:   0%|          | 0.00/23.0M [00:00<?, ?B/s]

Downloading model_quint8_avx2.onnx:   0%|          | 0.00/23.0M [00:00<?, ?B/s]

Downloading openvino_model.bin:   0%|          | 0.00/90.3M [00:00<?, ?B/s]

Downloading openvino_model.xml: 0.00B [00:00, ?B/s]

Downloading (…)_qint8_quantized.bin:   0%|          | 0.00/22.9M [00:00<?, ?B/s]

Downloading (…)_qint8_quantized.xml: 0.00B [00:00, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading (…)nce_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading tokenizer.json: 0.00B [00:00, ?B/s]

Downloading tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading train_script.py: 0.00B [00:00, ?B/s]

Downloading vocab.txt: 0.00B [00:00, ?B/s]

Downloading modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [9]:
# Create sentence embeddings for your sentences
sentences = ["This is an example sentence.", "Handling unknown words in embeddings is important."]
embeddings = model.encode(sentences, convert_to_tensor=True)

# The 'embeddings' variable now contains the sentence embeddings as PyTorch tensors
print(embeddings)
print(embeddings.shape)

tensor([[ 9.8125e-02,  6.7813e-02,  6.2523e-02,  9.5085e-02,  3.6648e-02,
         -3.9846e-03,  7.4776e-03, -1.3232e-02,  6.2884e-02,  2.2495e-02,
          7.2696e-02, -3.1274e-02,  4.6355e-02, -1.2554e-02,  4.7815e-02,
         -4.9103e-03,  4.9420e-02, -6.4109e-02, -9.6966e-02,  3.2889e-02,
          5.4104e-02,  3.5329e-02,  3.3051e-02,  1.4699e-02, -3.3431e-02,
         -2.5616e-02, -5.0792e-02,  7.3255e-02,  1.1027e-01, -2.9662e-02,
         -6.7557e-02, -3.0572e-02,  3.9560e-02,  4.5476e-02,  1.5996e-02,
          3.8550e-02, -1.0954e-02,  8.4836e-02, -4.4287e-02, -6.7964e-03,
          9.4256e-03,  5.0685e-05,  1.3036e-03, -1.1970e-02,  1.3645e-02,
         -8.4174e-02, -1.6515e-04,  5.4838e-03,  2.5615e-02, -3.1545e-02,
         -1.0734e-01, -4.5788e-02, -9.1175e-02, -2.5105e-03,  1.7998e-02,
          4.9402e-02,  6.1848e-03,  5.9796e-02,  2.7003e-02, -1.6122e-02,
         -1.8150e-02, -2.3635e-02, -9.4897e-02,  6.6216e-02,  1.4923e-01,
          2.4339e-02,  1.2102e-03,  6.0721e-03, -9.9170e-02,  8.5058e-02,
          3.0826e-02,  2.9187e-02, -2.3956e-02, -1.0559e-02, -7.2152e-02,
         -3.5256e-02,  3.3347e-02, -4.3930e-02,  1.1976e-01,  8.8647e-02,
         -9.5919e-02, -5.9080e-02, -8.2927e-03,  3.8169e-02,  4.9800e-02,
         -3.2682e-02,  1.9901e-02, -1.0838e-01,  1.4679e-02,  1.8118e-02,
         -6.1318e-02, -8.9750e-02,  4.9222e-02, -2.0871e-02,  4.0550e-03,
         -3.5430e-02, -5.6578e-02, -4.8314e-02, -2.4660e-02,  7.3592e-02,
         -2.0924e-02,  4.0698e-02,  3.2327e-02,  7.6683e-02, -1.4748e-02,
         -1.0305e-01, -4.2745e-02, -6.6293e-02,  1.5474e-02, -2.6800e-02,
         -9.1752e-02, -3.5600e-02, -1.8933e-02, -4.0296e-03, -2.0193e-02,
         -5.8535e-02, -1.0180e-01, -4.4878e-03, -6.9763e-02,  6.0241e-02,
          2.9811e-02,  6.3808e-02, -6.7306e-02,  3.3509e-03, -6.0040e-02,
         -9.3137e-02,  4.5675e-02, -6.7199e-33,  7.4332e-03, -6.5110e-02,
         -2.1259e-02,  3.5196e-02,  4.6336e-02, -7.0305e-02, -6.1290e-02,
          1.7367e-02, -7.4798e-03, -1.8469e-02,  1.6074e-03, -2.5802e-02,
          3.0047e-02,  8.7516e-03,  5.0930e-02,  7.1716e-02, -7.2718e-02,
          1.3262e-01, -8.0341e-03,  3.6932e-02, -2.3691e-02,  2.4269e-02,
         -2.6396e-02, -1.8338e-02, -1.4753e-02, -7.4317e-02,  1.6345e-02,
          1.8037e-02, -3.1233e-03,  4.1283e-02,  5.0599e-02,  4.4495e-02,
         -4.7553e-02, -2.6265e-03,  5.4668e-02,  4.6978e-02,  6.3798e-02,
         -2.1837e-02,  1.1920e-03,  6.1550e-03, -1.0475e-02, -5.1549e-02,
          2.1719e-02, -3.7872e-02,  8.7911e-02,  2.3658e-02,  1.9886e-02,
          2.1743e-02, -6.1921e-02,  2.0616e-02, -1.0687e-02,  5.7762e-02,
          5.9403e-02, -2.8876e-02,  6.9477e-02,  1.0137e-03,  4.2008e-02,
          3.4752e-02, -1.6647e-03, -1.0128e-02, -5.4720e-02,  4.0565e-02,
         -5.6016e-02,  5.7263e-02, -2.5761e-02,  2.9397e-02,  1.0299e-02,
         -4.9152e-02,  1.5428e-02,  2.8693e-02,  1.1681e-02, -6.9688e-03,
         -8.3468e-02,  1.0837e-01, -4.1983e-02, -4.2663e-02, -2.1897e-02,
         -2.1626e-02, -7.8522e-03,  3.8220e-02, -1.8009e-02, -1.4944e-01,
          2.3226e-02,  1.5029e-02, -3.9894e-02,  3.7517e-03,  4.3007e-02,
         -8.4755e-02, -3.0297e-02, -2.0131e-02, -2.5030e-02,  3.5259e-03,
          5.8235e-02,  5.4948e-03,  6.4898e-03,  3.1747e-33, -4.2438e-02,
          2.9922e-02, -8.8362e-02,  6.5753e-02,  1.0463e-01, -8.8967e-03,
          4.2894e-02, -9.5505e-02,  3.1682e-02,  7.3527e-02, -1.3085e-01,
          2.5530e-02,  1.6062e-02, -4.3756e-03,  2.9203e-02, -8.1341e-03,
          6.5257e-02,  6.2158e-04, -7.8358e-03,  4.1561e-02, -4.3720e-02,
          9.5040e-02, -2.5843e-02,  8.7017e-02, -4.1472e-02,  3.5440e-02,
         -1.4387e-02, -2.6075e-02, -9.5900e-02, -8.8815e-03,  7.0699e-03,
         -9.0524e-02, -7.9742e-02, -1.4228e-02, -5.3490e-02,  5.1226e-02,
          2.4541e-02, -3.6975e-02, -7.3411e-02, -6.8742e-03,  6.8126e-03,
         -3.2918e-02,  1.5791e-02,  1.0595e-01,  2.2715e-02, -5.6417e-02,
         -3.2064e-02, -1.0509e-01, -3.2905e-02,  5.1392e-02, -1.0035e-01,
          4.4995e-02, -3.2961e-02, -1.9641e-02, -1.0541e-01,  1.1974e-02,
         -1.1171e-02, -6.9577e-02, -9.7897e-03,  1.6011e-02, -5.1179e-02,
          8.7913e-03, -6.5762e-03,  6.6293e-02,  1.0956e-01, -5.4759e-02,
         -5.7093e-02,  5.0298e-02,  1.2622e-02,  2.8454e-02,  1.3438e-01,
          1.1014e-02, -1.5195e-01, -4.9476e-02, -6.5373e-02, -6.7092e-02,
         -6.9697e-02, -3.1296e-02, -6.1766e-02, -7.4204e-02,  2.8974e-02,
         -8.3125e-03,  4.3219e-02, -1.7557e-02, -5.1787e-03, -5.4324e-02,
         -4.1276e-02, -8.2707e-02, -1.5987e-02,  8.6180e-03,  6.2553e-04,
         -6.5235e-02,  7.9263e-02,  2.6802e-02, -2.5414e-02, -1.9652e-08,
         -2.2533e-02, -1.5101e-02,  8.1941e-02, -3.9590e-02,  4.7111e-02,
          1.5206e-02,  6.5377e-02,  1.8435e-02, -7.9717e-03, -3.7731e-02,
          2.3044e-02,  4.0450e-02, -5.6972e-02, -3.0700e-03,  5.3666e-02,
          6.0949e-02,  3.8315e-02, -3.8076e-02, -2.6754e-02,  6.7404e-02,
         -5.4177e-02,  4.5898e-02, -1.2909e-02,  1.5068e-02,  3.3009e-02,
          4.9808e-03,  4.3409e-02,  6.5190e-02,  1.6216e-02,  3.6137e-02,
          5.5674e-02,  1.1904e-01,  2.4057e-02,  1.5142e-02,  6.0564e-02,
          3.6820e-02,  4.1256e-02, -3.1559e-02,  5.6254e-02, -2.5756e-02,
          1.3329e-02,  4.8441e-02, -2.1775e-02,  1.1008e-01,  3.8590e-02,
          3.8059e-02, -4.8710e-03, -4.3283e-02, -2.5374e-02,  1.6014e-02,
          1.8331e-02,  5.6381e-02,  3.4615e-02, -2.0660e-02,  2.1278e-02,
          1.8938e-02,  3.3834e-02, -6.9624e-03, -2.4326e-02, -1.9780e-02,
         -1.9895e-02,  3.4644e-02,  4.9627e-02, -2.9213e-02],
        [-2.8377e-02, -2.0708e-03,  5.4685e-02,  1.2883e-02,  7.1101e-03,
          5.8871e-02,  1.9502e-02, -5.8214e-02,  2.3845e-02, -2.6819e-02,
          4.1482e-02,  5.8580e-03,  1.1217e-01,  2.2520e-02, -5.4085e-02,
          5.6741e-02,  5.2213e-02,  1.0743e-01, -9.5484e-02, -4.1371e-02,
         -5.9803e-03,  2.7148e-02,  3.0960e-02, -6.1070e-02,  5.3113e-02,
         -1.6393e-04, -7.6369e-02,  3.2172e-02,  4.7020e-02, -1.9154e-02,
          6.4955e-02,  5.5648e-02,  1.1810e-02,  5.3889e-02,  4.1931e-02,
          7.9822e-02, -2.5251e-02,  1.3288e-03, -5.2539e-02, -1.4109e-02,
         -6.7111e-04,  3.4043e-02, -5.2940e-02,  8.2960e-02,  5.1950e-02,
         -5.4564e-02, -5.2918e-02, -2.6814e-02, -4.0311e-02,  9.2200e-03,
         -4.8382e-02, -6.1967e-02, -7.2726e-02,  3.1427e-02, -8.0908e-02,
         -6.6859e-02,  1.0755e-02, -5.2534e-02, -1.6892e-02, -1.4073e-02,
          1.2351e-03, -3.8583e-02,  5.9797e-02,  2.4249e-02,  1.3190e-02,
         -5.7071e-02, -1.6109e-02,  7.7472e-02, -2.0916e-02,  1.3286e-01,
         -8.3279e-03,  7.6316e-02, -8.6815e-02,  5.6501e-02, -3.5391e-02,
          2.1978e-02,  2.2358e-02, -8.7429e-02,  8.6523e-02, -4.4556e-02,
          2.9058e-02, -4.3182e-02,  2.4916e-02, -1.3933e-02,  1.1222e-01,
          4.1149e-02,  5.8479e-02, -6.6415e-02, -4.3064e-02, -3.2018e-02,
         -4.9018e-02, -1.6383e-01,  8.2090e-02,  4.3836e-02,  9.0925e-02,
         -2.1006e-02,  6.4045e-03, -1.1872e-03, -1.1338e-03,  5.3594e-02,
         -4.7044e-02,  3.0674e-02,  7.1290e-02, -1.0815e-02, -6.5639e-02,
         -4.9462e-02, -3.4392e-02,  7.4315e-03, -4.2091e-02, -8.5476e-02,
         -6.2124e-02, -7.3399e-03, -2.1385e-02,  1.3101e-02,  5.5455e-03,
         -2.6081e-02,  8.4589e-02, -2.0983e-02,  3.1077e-02,  1.8508e-02,
         -7.4617e-02,  6.6205e-02,  5.8486e-02,  3.3032e-02, -3.0622e-02,
         -6.2429e-02, -6.0843e-03, -2.6675e-33,  1.3337e-02,  2.6506e-02,
         -5.9429e-02,  6.4780e-02,  3.0246e-02,  3.5750e-02, -5.1359e-02,
          4.3867e-02, -2.1808e-02,  1.8623e-02, -1.2981e-02, -1.6333e-02,
          1.8651e-02,  6.3282e-02,  3.9952e-03, -4.1279e-04,  2.5117e-02,
          2.4031e-02, -1.1452e-02, -5.8875e-02,  2.7286e-02,  2.5233e-02,
         -4.5967e-02, -7.1504e-02, -1.1288e-01, -2.0846e-02,  6.1113e-02,
         -1.3848e-01, -1.3034e-02,  1.8545e-02, -7.9263e-02, -8.8457e-02,
          4.7801e-02,  1.9035e-02,  2.4740e-02, -1.8229e-02,  9.3307e-03,
         -2.5745e-02, -3.5446e-02, -5.1210e-02, -4.1525e-04,  5.9769e-03,
         -6.7310e-03, -9.1918e-03,  2.1479e-02,  6.2031e-02,  6.4527e-02,
         -2.4705e-02, -5.0997e-02, -4.1106e-02,  2.6382e-02,  8.8306e-02,
          3.6686e-02, -4.4773e-02,  3.1831e-02, -4.6630e-02,  1.5264e-02,
         -2.1701e-02,  3.0695e-02, -8.7276e-02, -2.7784e-02,  5.2499e-03,
          6.1360e-02,  2.7133e-02,  1.3828e-02,  6.4499e-02, -2.1152e-02,
         -2.5577e-02,  7.9594e-03,  1.2564e-02, -4.9296e-02,  3.0475e-02,
         -4.3125e-02,  6.1401e-03, -5.0156e-02, -2.6087e-02,  7.0043e-03,
         -8.0255e-02,  4.8071e-02,  1.3579e-02,  3.1148e-02, -1.2823e-01,
         -1.8579e-02,  7.6233e-03, -1.0701e-01, -1.5122e-01,  1.2375e-01,
         -1.0198e-01,  3.2431e-02,  5.6128e-02, -3.0991e-02,  3.7660e-02,
         -1.0562e-01, -2.8373e-02, -1.4631e-02, -6.4562e-35, -3.4708e-02,
          2.9304e-02, -1.5468e-02,  1.3867e-02, -5.2033e-02,  1.2752e-03,
          1.9514e-02,  1.4563e-02,  6.2997e-02, -3.6890e-02, -7.8445e-02,
         -1.5853e-02, -7.9398e-03, -7.2276e-02,  3.3574e-02, -9.7930e-03,
         -3.0271e-02,  4.6992e-02,  3.5428e-02,  1.1224e-01,  3.6385e-03,
         -8.3654e-03, -6.1471e-02,  1.0167e-01,  9.6158e-02,  9.0540e-02,
         -2.9676e-03, -1.9391e-02, -8.2440e-02, -4.1784e-02, -2.7457e-02,
         -3.8917e-02, -5.3241e-02, -2.2904e-02, -1.0582e-01, -3.3289e-02,
          6.6531e-02,  3.8219e-02, -5.2783e-02, -1.3054e-02,  7.5441e-02,
          8.0780e-02, -1.6172e-01,  2.9158e-02, -3.6731e-02, -7.0176e-02,
         -7.4551e-02,  9.1131e-03,  5.7377e-02,  6.6628e-04, -7.8885e-03,
         -1.0664e-03, -4.5710e-02, -3.8957e-02,  4.5298e-02,  1.6543e-02,
         -9.0488e-03, -5.3403e-02, -6.1450e-03,  2.7366e-02,  3.0545e-03,
         -4.4792e-02, -2.4557e-02, -3.6458e-02,  2.3366e-02, -9.4189e-02,
         -7.2803e-02,  7.2313e-02,  1.5525e-02, -7.8321e-02,  2.2778e-02,
          4.7500e-03, -2.7646e-02, -1.2245e-03,  2.7298e-02, -9.1502e-03,
          5.5332e-02,  1.6349e-03,  3.8994e-02, -4.7696e-02,  4.1716e-02,
         -5.2192e-02,  1.1537e-01,  1.8951e-02,  5.3681e-02,  5.2626e-02,
          2.1040e-02, -3.0499e-02,  6.3155e-03, -3.9448e-02,  1.8414e-02,
          1.4316e-02, -3.9166e-02,  1.2462e-01,  3.6557e-02, -1.8083e-08,
         -6.3015e-02,  1.7914e-02,  3.4890e-02, -3.1697e-02, -6.5245e-03,
         -6.5785e-02, -4.1389e-02, -7.4511e-03, -4.7063e-02, -3.3918e-02,
          9.0082e-02, -2.5024e-02, -8.2822e-02,  4.5955e-03,  3.3518e-02,
          2.9939e-02,  1.6022e-02,  3.1670e-02, -2.3938e-02,  5.3119e-02,
         -6.4517e-03,  1.3342e-01,  6.3851e-03,  1.2320e-03, -2.9292e-02,
         -6.8123e-03, -5.0225e-03,  1.1277e-02,  7.3570e-02,  4.9295e-02,
          1.8487e-02,  4.8617e-02, -2.0766e-02,  1.3235e-03, -2.5739e-02,
          1.3179e-01, -1.5234e-02, -8.2515e-02, -7.6182e-02,  1.7251e-02,
          4.8231e-02,  1.9870e-03, -2.5199e-02, -2.6844e-02,  9.2802e-02,
         -5.0952e-03,  4.5828e-02, -3.6632e-02,  1.8111e-02, -6.2537e-03,
          2.2386e-02,  3.3222e-02, -2.3983e-02,  6.9537e-02,  6.1565e-02,
          6.6781e-03,  3.3813e-02,  3.8687e-02, -1.6755e-02, -3.0484e-02,
          9.7553e-03,  1.2364e-02,  4.6910e-02,  1.6053e-02]])
torch.Size([2, 384])

In [10]:
sample_size = 150000
df_queries_dataset_mini = df_reduced_queries_table.sample(sample_size, random_state = 42).reset_index(drop=True)
df_queries_dataset_mini.shape

(150000, 9)

In [11]:
product_cols = ['product_title', 'product_description', 'product_id']
df_products_dataset_mini = pd.merge(df_products_table[product_cols].drop_duplicates(), df_queries_dataset_mini[['product_id']].drop_duplicates() ,on = ['product_id'])
df_products_dataset_mini.shape

(139639, 3)

In [12]:
null_counts = df_products_dataset_mini.isnull().sum()
print(null_counts)

df_products_dataset_mini['product_title'] = df_products_dataset_mini['product_title'].apply(lambda x : str(x).lower() if pd.notna(x) else '')
df_products_dataset_mini['product_description'] = df_products_dataset_mini['product_description'].apply(lambda x : str(x).lower() if pd.notna(x) else '')
df_queries_dataset_mini['query'] = df_queries_dataset_mini['query'].apply(lambda x : str(x).lower() if pd.notna(x) else '')

null_counts = df_products_dataset_mini.isnull().sum()
print(null_counts)

product_title              0
product_description    68703
product_id                 0
dtype: int64
product_title          0
product_description    0
product_id             0
dtype: int64

In [13]:
queries = list(df_queries_dataset_mini['query'].unique())

step = 1000
query_dim = 384

cols = ['q' + str(x) for x in list(range(0, query_dim))] + ['query']
cnt = 0

for i in range(0,len(queries),step):
    
    cnt += 1
    # Define a list of sentences
    sentences = list(queries)[i:i+step]

    sentence_embeddings = model.encode(sentences, convert_to_tensor=True)
    
    df_tmp = pd.DataFrame(np.concatenate((sentence_embeddings, np.array(sentences).reshape(-1,1)), axis=1))
    
    df_tmp.columns = cols
    
    df_tmp.to_csv(
        f'query_{cnt}.csv', header = True, index = False)
    
#     if cnt == 2:
#         break
        
    print(i)

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000

In [14]:
gc.collect()

0

In [15]:
lst_product_title = list(df_products_dataset_mini['product_title'])
lst_product_description = list(df_products_dataset_mini['product_description'])
lst_product_id = list(df_products_dataset_mini['product_id'])

In [16]:
step = 1000
product_dim = 384

cols = ['p' + str(x) for x in list(range(0, product_dim * 2))] + ['product_id']\

cnt = 0
for i in range(0,len(lst_product_title),step):
    cnt += 1
    product_title_embed = find_embeddings(lst_product_title, i, "s")
    product_description_embed = find_embeddings(lst_product_description, i, "")
    
    # Concatenate arrays column-wise and reshape lst_product_id to (x, 1)
    df_tmp = pd.DataFrame(np.concatenate((
        product_title_embed,
        product_description_embed,
        np.array(lst_product_id[i:i + step]).reshape(-1, 1)
    ), axis=1))
    
    
    df_tmp.columns = cols
    df_tmp.to_csv(f'product_{cnt}.csv', header = True, index = False)
    
#     if (cnt == 2):
#         break
    
    print(i)

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

0

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

1000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

2000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

3000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

4000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

5000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

6000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

7000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

8000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

9000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

10000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

11000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

12000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

13000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

14000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

15000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

16000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

17000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

18000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

19000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

20000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

21000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

22000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

23000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

24000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

25000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

26000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

27000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

28000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

29000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

30000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

31000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

32000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

33000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

34000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

35000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

36000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

37000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

38000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

39000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

40000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

41000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

42000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

43000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

44000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

45000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

46000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

47000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

48000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

49000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

50000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

51000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

52000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

53000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

54000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

55000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

56000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

57000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

58000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

59000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

60000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

61000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

62000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

63000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

64000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

65000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

66000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

67000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

68000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

69000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

70000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

71000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

72000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

73000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

74000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

75000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

76000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

77000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

78000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

79000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

80000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

81000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

82000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

83000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

84000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

85000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

86000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

87000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

88000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

89000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

90000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

91000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

92000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

93000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

94000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

95000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

96000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

97000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

98000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

99000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

100000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

101000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

102000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

103000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

104000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

105000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

106000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

107000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

108000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

109000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

110000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

111000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

112000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

113000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

114000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

115000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

116000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

117000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

118000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

119000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

120000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

121000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

122000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

123000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

124000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

125000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

126000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

127000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

128000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

129000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

130000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

131000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

132000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

133000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

134000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

135000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

136000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

137000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

138000

/tmp/ipykernel_316/635942248.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return np.array(sentence_embeddings)

139000

In [3]:
gc.collect()

60

In [18]:
# Get a list of CSV files that start with "product_"
file_list = glob.glob('product_*.csv')

# Initialize an empty list to store DataFrames
dfs = []

# Read each CSV file and append it to the list
for file in file_list:
    df = pd.read_csv(file)
    dfs.append(df)

# Concatenate all DataFrames into one
concatenated_product_df = pd.concat(dfs, ignore_index=True)

# Save the concatenated DataFrame to a new CSV file
concatenated_product_df.to_csv('product_embeddings.csv', index=False)

print(concatenated_product_df.shape)

concatenated_product_df.head()

(277240, 771)

,p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,...,p761,p762,p763,p764,p765,p766,p767,product_id,product_title,pid
0,-0.038078,0.046183,-0.046560,-0.029900,0.033105,0.036471,0.026031,0.075297,-0.044393,0.024491,...,0.000266,0.008444,0.022443,0.025157,-0.112528,-0.013211,0.010067,B082BH7LTP,NaN,NaN
1,-0.026833,0.036172,-0.024524,-0.012489,0.041351,0.025878,0.023794,0.047958,0.000890,0.034477,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B008FOIUYQ,NaN,NaN
2,-0.027767,-0.002590,-0.024761,-0.017926,0.000495,0.021453,0.041093,0.133278,-0.064400,0.028866,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B00B9RKDNW,NaN,NaN
3,0.013659,0.020149,-0.058309,-0.037144,0.019248,-0.018274,0.113505,0.064983,0.021726,0.017442,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B00CF435PQ,NaN,NaN
4,-0.076317,0.100065,-0.125701,-0.031984,-0.044950,-0.039503,0.054975,0.083635,-0.067122,-0.052565,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B00CJ0TZ2S,NaN,NaN

In [19]:
# Get a list of CSV files that start with "product_"
file_list = glob.glob('query_*.csv')

# Initialize an empty list to store DataFrames
dfs = []

# Read each CSV file and append it to the list
for file in file_list:
    df = pd.read_csv(file)
    dfs.append(df)

# Concatenate all DataFrames into one
concatenated_query_df = pd.concat(dfs, ignore_index=True)

# Save the concatenated DataFrame to a new CSV file
concatenated_query_df.to_csv('query_embeddings.csv', index=False)

print(concatenated_query_df.shape)

concatenated_query_df.head()

(28394, 385)

,q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,...,q375,q376,q377,q378,q379,q380,q381,q382,q383,query
0,-0.030207,0.088923,0.073030,0.110539,0.084778,0.014884,0.060988,0.006597,-0.004667,-0.128469,...,0.018233,-0.023314,-0.024556,-0.031398,-0.042695,0.061797,0.009030,-0.014782,-0.054768,morning recovery
1,-0.064102,0.023352,-0.041795,0.023195,0.081636,-0.017785,-0.005570,-0.009171,0.032116,-0.042893,...,-0.036001,0.000856,-0.057846,-0.112102,0.029485,0.031720,-0.028930,-0.015094,0.068795,lowes
2,0.013132,0.072070,-0.065992,-0.002896,-0.040129,0.013525,0.012280,-0.013594,-0.027428,0.057251,...,0.042006,0.093058,-0.018531,-0.044261,0.036163,0.088064,-0.001749,-0.007720,0.037286,task chairs without arms 300 lb
3,-0.039690,-0.034436,-0.005114,-0.038683,0.040749,-0.068795,0.187906,0.036407,-0.022499,0.017866,...,-0.132944,0.050967,0.103548,0.003425,-0.065521,-0.063869,0.011004,-0.062140,0.046877,contact lens colored for eyes
4,-0.026860,0.098137,-0.010122,-0.067484,-0.046869,-0.006085,0.006388,-0.044399,-0.057481,-0.047813,...,0.014596,0.012656,0.028947,0.140658,0.003223,-0.049562,0.096512,-0.011497,-0.064696,plates to paint and decorate

In [20]:
df_queries_dataset_mini  = pd.merge(df_queries_dataset_mini, concatenated_query_df, on = 'query')
df_queries_dataset_mini  = pd.merge(df_queries_dataset_mini, concatenated_product_df, on = 'product_id')

print(df_queries_dataset_mini.shape)

df_queries_dataset_mini = df_queries_dataset_mini.drop_duplicates()

df_queries_dataset_mini.head()

df_queries_dataset_mini.to_csv('dataset_mini.csv', header = True, index = False)

(302728, 1163)

In [6]:
df = pd.read_csv("./dataset_mini.csv")
print(df.head())
df.shape

   example_id                             query  query_id  product_id  \
0       27501  1.0 reading glasses without ears       967  B085G83F81
1       27501  1.0 reading glasses without ears       967  B085G83F81
2     2217414           words i could not write    113782  1975778375
3     2217414           words i could not write    113782  1975778375
4     1833968                simpsons bart soul     93686  B07YQB32KK

  product_locale esci_label  small_version  large_version  split        q0  \
0             us          E              1              1  train  0.051139
1             us          E              1              1  train  0.051139
2             us          E              1              1  train -0.020010
3             us          E              1              1  train -0.020010
4             us          I              1              1   test -0.037605

   ...      p760      p761      p762      p763      p764      p765      p766  \
0  ...       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1  ...  0.042288  0.006759 -0.087325 -0.008156  0.114574  0.007143 -0.064455
2  ...  0.013367 -0.012748  0.061454  0.035641  0.158746  0.126410  0.046549
3  ...       NaN       NaN       NaN       NaN       NaN       NaN       NaN
4  ...  0.000998  0.093577 -0.098183  0.052911 -0.007097 -0.032590  0.012956

       p767                                      product_title       pid
0       NaN  Gaoye 5-Pack Reading Glasses Blue Light Blocki...  115174.0
1  0.053950                                                NaN       NaN
2 -0.015717                                                NaN       NaN
3       NaN  Letters from a Vietnam Vet: Words I Could Not ...   30150.0
4 -0.027994                                                NaN       NaN

[5 rows x 1163 columns]

(302726, 1163)

In [2]:
df_products_table = pd.read_parquet('../shopping_queries_dataset/shopping_queries_dataset_products.parquet')

df_product_embedding = pd.merge(
    pd.read_csv('./product_embeddings.csv'),
    df_products_table[['product_id','product_title']],
    on = ['product_id']
).reset_index(drop=True)
df_product_embedding = df_product_embedding.drop_duplicates()


df_product_embedding['pid'] = range(0, df_product_embedding.shape[0])

/tmp/ipykernel_884/1342393268.py:4: DtypeWarning: Columns (0: product_title) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('./product_embeddings.csv'),

In [ ]:

df_query_embedding = pd.read_csv('./query_embeddings.csv')
df_query_embedding = df_query_embedding.drop_duplicates()

df_query_embedding['qid'] = range(0, df_query_embedding.shape[0])
df_query_embedding.head()

In [7]:
# Remove a column named 'old_column'
# Rename 'old_name' to 'new_name'
df_product_embedding = df_product_embedding.rename(columns={'product_title_y': 'product_title'})
df_product_embedding.head()

,p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,...,p761,p762,p763,p764,p765,p766,p767,product_id,pid,product_title
0,-0.038078,0.046183,-0.046560,-0.029900,0.033105,0.036471,0.026031,0.075297,-0.044393,0.024491,...,0.000266,0.008444,0.022443,0.025157,-0.112528,-0.013211,0.010067,B082BH7LTP,0,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...
1,-0.026833,0.036172,-0.024524,-0.012489,0.041351,0.025878,0.023794,0.047958,0.000890,0.034477,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B008FOIUYQ,1,Utopia Towels Cotton Bleach Proof Salon Towels...
2,-0.027767,-0.002590,-0.024761,-0.017926,0.000495,0.021453,0.041093,0.133278,-0.064400,0.028866,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B00B9RKDNW,2,Bio Plas 0090 Polypropylene 96 Well Reversible...
3,0.013659,0.020149,-0.058309,-0.037144,0.019248,-0.018274,0.113505,0.064983,0.021726,0.017442,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B00CF435PQ,3,Tube Color Storage Rack - 3 Pack
4,-0.076317,0.100065,-0.125701,-0.031984,-0.044950,-0.039503,0.054975,0.083635,-0.067122,-0.052565,...,-0.012748,0.061454,0.035641,0.158746,0.126410,0.046549,-0.015717,B00CJ0TZ2S,4,Pana Black 6 Tier Large Wall Mounted Metal Rac...

In [9]:
print(df_query_embedding.shape, df_product_embedding.shape)

(28394, 386) (283691, 772)

In [10]:
query_tower_input_dim = 384
product_tower_input_dim = (384*2)

q = AnnoyIndex(query_tower_input_dim, 'dot')
mp_query_dict = {}


for ix,row in df_query_embedding.iterrows():
    mp_query_dict[row['qid']] = row['query']
    
    key = int(row['qid'])
    vec = list(row[['q'+str(x) for x in list(range(query_tower_input_dim))]])
    
    #     print(key,vec)
    q.add_item(key,vec)


q.build(100) # 100 trees
q.save('query.tree')

top_k = 20
mat = []
for ix,row in df_query_embedding.iterrows():
    item = row['query']
    mat.append([item] + [mp_query_dict[x] for x in q.get_nns_by_item(row['qid'], top_k+1)[1:]])
    
    if ix == 50:
        break
    
cols = ['query_id']
for i in range(top_k):
    cols += ['nearest_{}'.format(i+1)]

df_neighbors1 = pd.DataFrame(mat, columns = cols)

display(df_neighbors1.head(50))

,query_id,nearest_1,nearest_2,nearest_3,nearest_4,nearest_5,nearest_6,nearest_7,nearest_8,nearest_9,...,nearest_11,nearest_12,nearest_13,nearest_14,nearest_15,nearest_16,nearest_17,nearest_18,nearest_19,nearest_20
0,morning recovery,morning recovery original,ok to wake clock,c-50 blemish night treatment,i’m tired of waking up and not being in maui,booty enhancing drink,light therapy insomnia,healing depression without medication,timely alarm,sleep supplement without melatonin,...,bedtime press,alarm clock without snooze,natural sleep aid without melatonin,lin manuel miranda good morning good night,dreamstation,best sleep aid for insomnia,sleepless in southampton book,maxi nursing nightgown,joerns hospital bed,lifesaver
1,lowes,nootropics depot,parker s huntington,mainstays kitchen,marshall stanmore 2,kc mills,lawn trencher,u-line refrigerator,wrench arborist,inc,...,houses,lucinda s kitchen,pet co,lori wall bed,kitchen cabinets,nls,pipe,dyson hairdryer,taos te,profloss
2,task chairs without arms 300 lb,ergonomic desk chair no arms,lobby chairs without arms,gaming chair for adults 300lbs,upholstery arm chairs,gaming chair 300 lb weight capacity,balance chairs,low back desk chair without arms,bungee office chair without arms,lawn chair without arms,...,rolling desk chair without arms,chairs without wheels,gaming chair 500lb weight capacity,steno chair without arms,0ffice chairs without wheels,chair covers for office chairs without arms,wood desk chairs without wheels,desk chairs without wheels for kids,ergonomic office chair without wheels,home office chair without wheels
3,contact lens colored for eyes,colored contact lenses,color contact lenses,color contacts lenses for eyes non prescription,contacts lenses for eyes cosplay gray,white contact lenses,contacts lenses,halloween colored contacts,gold color contacts,light green contacts,...,blue light glasses without yellow tint,bike sunglasses night lense,canon red ring lenses,celestron lens shade,white shades glasses for women,blue light glasses kids,goggles for led light therapy,red eagle eye led lights,optcon a eye drops,under armour sunglasses for men pink
4,plates to paint and decorate,garden party plates,wood look paper plates,christmas plates,burlap look paper plates,kids porcelain plates,paper bowls and plates,ceramic plates,"7"" paper plates",pastel unicorn party plates,...,floral dessert plates,front plates for cars hi,pink shell plates,joy ceramic plates,plate for baby sheet,kids plates not plastic,plastic plates and forks,disposable plates,cow paper plate,black plate set
5,kids clothes 12 years,9 year old clothes,kid 9 clothes,fashion show clothes for kids,2 year old boys clothes,kids winter clothing,kids clothing sets for boys,teen girl clothes 13 years old,baby girl 6-9 months winter clothes,dress up clothes for little girls,...,kids dress,vintage newborn boy clothes,0-3 month boy fall clothes,cute girl outfits age 9,dinosaur clothes children,winter cozy toddler girl clothes,baby dress up clothes,long sleeve shirts for kids,art supplies for kids age 7-9,vans toddler clothes
6,ergonomic desk chair without wheels,ergonomic office chair without wheels,home office chair without wheels,desk chair without wheels cheap,small office chair without wheels,white desk chair without wheels,wood desk chairs without wheels,office chair without wheels or lift,gaming chair without wheels,adjustable chair without wheels,...,ergonomic desk,kids office chair without wheels,ergonomic desk chair no arms,office chair no wheels,desk chairs without wheels for kids,rolling desk chair without arms,ergonomic chair wooden,office chair not on wheels,desk chair for teens girls without wheels,foldable ergonomic chair
7,gacha life,gakus,ghibli,lifesaver,streigh gama,apha goc,uludag gazoz,pista,detective pikachu,zh,...,zervos,zerplus,sal and gabi break the universe,life on the line movie,grode,lunir,naruto kunai,hard zelter,lifes too short abby jimenez,pixie
8,34 curvy jeans,"stretchy skinny jeans, dark brown",35x29 mens jeans,curvy jeans for women high waist,high waist jeans,high waisted baggy jeans,jeans clothing,plus size jeans for women,levi 721 high rise skinny jeans for women,black jeans 8 years old girls,...,mens jean shorts 32,highwaisted white jeans,black wide jeans for women,mens 38x34 jeans relaxed fit,mom jeans high waisted vintage,black jeans for women high waist,size 16 white jeans for girls,star jeans,levis 513 slim straight stretch jeans,ripped high waistef black jeans
9,gun slings and swivels,shotgun sling without swivels,airsoft sling,russian ak sling,sling blade,bobath sling,carbines pull straps,shotgun rear pistol grip,buckle gun roll,kids ride on slingshot,...,handgun,polaris slingshot shocks,rifle mount,hex brand camera sling,bb-gun rifle,harris swivel bipod 6-9,pistols,strong airsoft guns,shotgun shell pouch,strap for nerf gun
10,two yr old girls toys,1 year old girl toys,1 1/2 year old girl toys,toys 2 year old girl,girl toys age 1,toddler toys for girls age 2,girl toys,toys for 2 year girl,toys for 1 year old girl,toys for 1year old girl,...,toys for 8 year old girls,girl toys for girls ages 8-12,2 yr old boy toys,2t baby girl toys,girls riding toys age 6-9,toys for 7 year olds girls,educational toys for 2 year olds,2 year old boy toys,toys for girls 8 to 12,1-year old toys
11,hair coloring brush,circular hair brush,dye spray for hair,rinse hair color,new artist paint brush,kirby allison medium horsehair shoe polishing ...,saphir horsehair brush,paint brush container,round hair brush for men,coniar hairbrush,...,hair dye for dogs,best brush for dogs with hair not fur,hair bleach,hair dye for dark hair without bleach,lilly brush,mustache dye,"sonicare brush, w",siamond clean brush,hair dye white permanent,purple hair dye for dark hair without bleach
12,chrome,laptop not chromebook,chromecast,like to have google chrome on it. must not be ...,google home,computer,googleamazon,cs,apps,cookies,...,samsung chrome notebook model xe500c13 case,mouse,acer spin chromebook 15,google computers devices,proclick,kids youtube,arduino,engine,computer fortnite,alexa video
13,samsung note 9 case,samsung galaxy note 9 cases,galaxy note 10 plus case,note 10 plus case,galaxy s9 phone case,designer galaxy s9 case,galaxy note 10 case black,samsung s10+ case,samsung s8 case,case samsung galaxy s9 plus girls,...,samsung note 10,cosmo phone case galaxy s9 plus,magnet phone case for samsung galaxy note 10 plus,samsung galaxy note 10 case not plus,galaxy s10 plus case,galaxy s10 metal case,samsung note 10 plus cover,samsung tablet case 8 inch,samsung galaxy note 10 plus,galaxy note 10 plus
14,shaklee cleaning products,clean and perfect cleaner,commercial steam cleaner detergent,swiffer wet jet cleaner solution,cleaning supplies,wax warmer cleaner,hand cleaner without pumice,felco cleaning,norelco razor cleaner,afresh washer machine cleaner high efficiency,...,disinfect ting wipeswipes,shooterlube gun cleaner solvent,virginal cleaning for women,dremel cleaning tool,nuvera bbq grill cleaner degreaser,teakguard super cleaner,gunzilla gun cleaner,tweezers cleaner,suede cleaner for shoes,disinfecting wipes
15,yoga prop,yoga foot,clever yoga mats,white yoga mat,yoga base board,yoga365,veniasa yoga mat,yoga mat 1 inch,yoga mat black and white,giam yoga ball,...,yoga swing without handles,kingjoze high waisted yoga shorts,yoga strap without buckle,thick maternity yoga pants,yoga mat towel non slip gaiam,yoga tops for women short sleeve,rockets wristband,workout belt rouge,pole dance mat,strapless tummy control shapewear
16,dorm room essentials for guys,dorm room essentials,college dorm room essentials,room supplies for teen girls,cute room stuff for teen girls,room asseccories for men,dorm appliances,basic open hamper white - room essentials™,bedroom clothing set,airbnb essentials,...,room decor for teen girls,mint green rugs for girls rooms,male hygiene travel kit,wall stickers for bedroom girls personalizado,pink and gold decor for girls room,printer for dorm rooms,men's pajamas,gifts for teenage boys,black bandana bedroom set,cute room decor for teen girls
17,water resistant down knee length parka,waterproof tactical shorts-,cold water knee therapy system,ski knee pad,water and snow resistant boots,water proof waist bag,falltech water,outdoor waterproof slippers,pleated skirts for women knee length,running shorts without liner,...,sorel rain boots for women waterproof,tall rain boots for women,quilted riding boots for women waterproof,swim parkas for women,water sandals,cycling shorts without padding,above ground slide for pool,waterproof rain jacket and pants,high waist shorts bathing suit,plus size fishnet thigh highs with back seam
18,squeaky balls for large dogs,plush dog toys without squeakers,wicked ball for dogs,dog toy without squeaker,small ball pit,kong dog toys for aggressive chewers,6 inch styrofoam balls,ball pits for toddlers,indoor tennis ball games for dogs,big dog pillow for large dogs,...,fuzzy white balls,christmas balls big,plastic balls for tee ball set,20 lb medicine balls rubber,large inflatable soccer ball,dog seat for large dogs,elbow pads for dogs,250 bouncy balls,double bubble mini gumballs,kong dog tug toy
19,techo para patio sombra,plantas solares para casa,regadera para plantas de mano,sillas redondas para sala,vasija para almuerzo calentadora,bebederos de agua para pajaros,storage patio plastico,patio bars,bomba sumergible para estanque,woodard patio,...,soporte microfono,tepui rooftop tent,rompope mexicano,ensimas dijestibas organica,pantalo comando,panales para perrito desechables,zapatos elegantes para hombres,plástico de burbujas para embalar,outside screen for patio,paquete de llaveros new york
20,leo mckern,michael gelb,roy vickery,michael j fox,lawrence schoen,mickey mouse binky,sergio marchionne,rapunzel erik,matthew gray gubler,kcogear,...,john elliott,patrick custome,mickey rapkin,ted nasmith,bernie mac,zodiac,colster,robert cray stratocaster,petechtool,dji robomaster
21,indian oil painting,oil paints for canvas,new artist paint brush,deco art paint,flat black angelus paint,simplistic large painting,warhammer paint,cabinet painting supplies,graffiti spray paint,indian hair mask,...,verde green hammered spray paint,animal painting with flower crown set of two,to paint without thinking,artist loft pouring acrylic paints,oriental wall murals,dh oil,orange textured paint,western black and white wall art,art of aromas posters,semigloss spray paint rgey
22,jason biggs,jason bag,jeff shalfon the family,jason hand soap,the dude big lebowski,brian billick,david suchet,the big easy,dr jason fung books,charles duncan,...,john green,james goll dreams,robert iger,kamado big joe iii,greg stone,roy vickery,marcus luttrell,philadelphia eagles dad,cleveland big and tall,kenny loggins
23,designer dupe jewelry,make jewelry,new design necklace,vintage antique jewelry,jewellery bulk,shinelife jewelry,jewelry stainless steel,jewelry for girls,jewelry bar,tiffany jewelry,...,unicorn jewelry,colelge jewelry,colorful diamond necklace,gold pearl necklace,silver crystal necklace,brilliance jewelry wedding bands,ganz jewelry,2mm diamond necklace,pearl silver lariat necklace,chandelier necklace
24,clutch purse,nude purse clutch,purse,wallet purse,travel purse,professional purse,purse backpack,mk purse,mk purses and handbags,mens purses and handbags,...,small scrunch up purses,aldo purses and handbags,louis vuitton purses,canvas lightweight purses,purse organizer zip pouch,million dollar purse,leather small shoulder purse,stegosaurus purse,coin purse emoji coin purse,gucci purse
25,bad donkey hat,teddy bear hat,gangster hat,hard hat,clever hat,wool bucket hat,gold cowboy hat,bad bunny,deer patch hat,shell hat,...,baby hat black,blue round hard hat,mad hatter hat,hoodie hat,sheep skin hat,lean cup hat,home depot hat,giant genie hat,flat brimmed hat,gardening hat
26,statistics by peck,bird sounds book,lee smith books,rudin by ivan turgenev,verity by colleen hoover,western books by cole,book by greg jarrett,the new jim crow by michelle alexander,this is water david foster wallace book,haban book,...,top gun book,ed stack book,mark few gonzaga book,free samples,pin collector book,tucker carlson books,hillary clinton book,on the black hill by bruce chatwin,poor mans cookbook,the new jim crow study guide
27,kettlepizza,lavazza coffee machine,pot,tea pot charm,mango bubbly,peach,le creuset teapot,pixie,chinese steamer,ethiopian tea,...,cup of tea,kambiz,babadook,bohio coffee,silver pooja pot,teal bowl,giorello,kettle corn popcorn,maggie hot and sweet sauce,paiste gong 32
28,beauty pageant,amara beauty,no beauty without danger,bride costume for girls,bodycon flower dress maxi,beauty and the beast cake decorations,very little sleeping beauty,beauty and the beast costume for dog,makeup vanity,princess belle costume for girls disney,...,modest bikini,huda beauty 420,halloween gown for women,boho homecoming dresses,black widow costume for women,teaparty dress,childs sleeping beauty costume,elsa costume for girls,scarlet witch costume,girl butterfly dress
29,valentine cards for kids school,gift cards for kids,valentines preschool,schoolmaskpack for kids,toddler girl valentine,amazon gift cards for christmas,boys wallets for teens,christmas gifts for teen girls 14,smart gifts for kids,birthday gifts for pre-teens,...,gifts for college kids,hallmark shoebox funny christmas cards,english spanish flash cards for kids,netflix gift cards,kids army school supplies,bulk gift for kids,christmas gifts for teen girls,days of the year calendar for kids,religious bulk christmas cards,back to school supplies for girls
30,eggs brown cage free,eggs brown large,king size egg crate,poached egg pan,green egg,animal cage,black fly larvae egg,egglettes egg cooker - hard boiled eggs withou...,hamster. cage,egg life egg white wraps,...,womens egg costume,green egg accesssories digiq,parakeet silo feeder clean,green egg lump charcoal,cage for dogs travel,guinea pig cage,hamster cage tubes,big hamster cage,salmon eggs for trout fishing,two tier hamster cage
31,1 1/4 leather belt without buckle full grain,1 1/2 leather belts without buckle,1 1/8 skinny leather belts without buckles,1 inch leather belt without buckle,1 '' leather belts without buckles,1.75 leather belts without buckles,11/4 leather belt without buckle,0.75 width leather belt without buckle,leather belt blanks 1 1/4 inch,1.2 inch belt without buckle,...,1 1/2” wide mens belt without buckle,mens belt without buckle leather,1 3/4 inch tooled belt strap without belt buckle,1 in. mens western belts leather without buckle,1 in wide belt without belt buckle,leather belt without holes,1 1/8 womensleather belts without buckles,1 1/2 inch wide belt strap without buckle with...,nylon belt without buckle,high waist leather leggings with belt
32,classic van's men old school,vans shoes men,vans men shirt,van girls size 3,vans sweatshirt,vans toddler girls,vanderpump season 8,80’s movie,officer and a gentleman dvd,80s kids,...,80s movies,professor costume men,terry slippers,the summer without men,dinosaur mens onsie,alex holland,movies we shall not grow old,music caravan,adult books,vanlov human hair wigs
33,thin leather strap,24mm leather watch strap,apple watch band double strap leather,1 3/4 mens leather belt strap without buckle,leather small shoulder purse,black suede shoe strap,watch for women waterproof leather strap,apple watch band holder case in leather,hand sewing leather bags,luggage buckle strap,...,bag chain strap,fitbit charge 2 leather band,wristlet wallet with cell phone holder leather,1 inch leather belt without buckle,1 '' leather belts without buckles,15 mm watch strap,leather hat bands,skinny lanyard,canvas stripe apple watch strap,1 1/8 skinny leather belts without buckles
34,mckenzie childs flatware,infant twin items,kids mac miller vinyl,baby gift set,baby boy clothes onesies,baby basket stuffers,kid 9 clothes,green bay packers toddler apparel,toddler sports bedding,thing 1 kids shirt,...,buffalo plaid baby boy,5 dollar items for kids,boy kid apron,boho toddler girls sets,baby nursery closet,vans toddler clothes,toddler bed sets for boys,kids slime apron,halloween jammies toddler,twin boys tshirt
35,accessories to make my nails strong,nail stuff to hold finger nail supplies,killer nails supplements,nail strengthener for gel polish,nail polish & decoration products,navy pro tools nails,press on nails without glue,performance health one hand nail clipper,chorme nails,gel press on nails,...,gel nail strips sally hansen,nail swatch sticks,nail not tool,press on gel nails bulk,pole nail gel,nail tips acrylic,dab rig electronic nail kit,hang without nails,baby nail clippers and brush set,bed of nails puzzles
36,hot glue gun,ultra low temp glue gun,glue gun sticks,lego glue,car glue,original crazy glue,hot cheese gun,1 inch binder4 oz elmer glue,4 x 28 mini hot glue sticks,wig glue spray,...,nail foil glue,got 2b glue wig glue,gun,tray holder glue,build plate glue,craft glue for kids,glow in the dark glue,fake gun,crimper hair iron hot tools,electric grease gun
37,loafers women stylish platforms,white platform booties costume women,womens gold loafers,wide width penny loafers for women,women design,castle x platform jacket womens,slouchy womens boots,assets shapewear for women,calvin klein sleepwear women,boots without heels for women,...,utility pants women,fur lined boots women,starbucks outfit women,capri joggers womens plus,long boots women,outfits for women night out,roxy boots for women,yellow platform sneaker for women,woman penny loafers shoes,boutique clothing for women
38,06 saturn ion fuel pump assembly without pump ...,air bed without pump,portable gas pump,queen air mattress without pump,quincy compressor pump,bicycle inflator pump,presta valve electric bike pump,ka24de oil pump,intex twin air mattress with built in pump,battery operated balloon pump,...,inflatable full mattress with built in pump,ford 5.0 electric water pump,07 nissan pathfinder window regulator without ...,toilet with pump,manual shallow well pump,10x30 pool without pump and filter,- dash air vent outlet assembly without air co...,hydraulics pumps,1.8 inch soap dispenser pump replacement witho...,0-15 psi fuel pressure gauge not liquid filled
39,spaghetti strap summer dress,maternity dress spaghetti strap,spaghetti strap tiered maxi dresses for women,summer dresses,tube summer dress,sling floral print sling casual sleeveless max...,tank top dress summer,overall skirt outfit summer,silk mini dress,long sleeve evening dress,...,mesh blue sequin dress,sweater dress for juniors,swing dress,white wrap maxi dress,band tshirt dress,yellow polka dot dress,dress watch,big stomach dress,swim dress,midi flowy dress
40,light blue intense dolce and gabbana women,womens sexy bodycon dress blue,dolce gabbana runway,pink and blue tshirt women,navy blue sexy dresses for women,royal blue striped shirt women,leather vintage belt brown womens,royal blue suit for women,blue sexy top,navy blue tops for women,...,blue earrings for women,pink boas for women,yellow and black dresses for women,belts for women sparkle,women navy blue columbia shirts,women of lights,camisole leotard women,rainbow brite costume women,bulgari blue perfumes for women,adidas ultra women stella
41,0.9%sodium chloride without any preservatives,0.9% sodium chloride without preservatives usp,salt substitute without potassium,1% retinol organic without carageenan,"100% organic, pure without any mix",00% natural ingredients not 100% vitamin e,salt pills with electrolytes,utz chips no salt added,1 morton sea salt without iodine,toothpaste without sodium lauryl sulfate,...,hay preservative,mill pepper and salt,celery salt,ezikel bread low sodium,retaine eye drops for dry eyes preservative free,cheddar popcorn salt,nasal rinse salt packet,case of limon 7 salt,bole salts,pure encapsulations nutrient 950 without iron

In [8]:
product_tower_input_dim = (384*2)
p = AnnoyIndex(product_tower_input_dim, 'dot')
mp_product_dict = {}

for ix,row in df_product_embedding.iterrows():
    mp_product_dict[int(row['pid'])] = row['product_title']
    
    key = int(row['pid'])
    vec = list(row[['p'+str(x) for x in list(range(product_tower_input_dim))]])
    
#     print(key,vec)
    p.add_item(key,vec)
    if ix == 50:
        break
    

p.build(100) # 100 trees
p.save('product.tree')


p = AnnoyIndex(product_tower_input_dim,  'euclidean')
p.load('product.tree')



top_k = 20
mat = []
for ix,row in df_product_embedding.iterrows():
    item = row['product_title']
    mat.append([item] + [mp_product_dict[x] for x in p.get_nns_by_item(row['pid'], top_k+1)[1:]])
    
    if ix == 50:
        break
    
cols = ['product_id']
for i in range(top_k):
    cols += ['nearest_{}'.format(i+1)]

print(cols)

df_neighbors2 = pd.DataFrame(mat, columns = cols)

display(df_neighbors2.head(200))

['product_id', 'nearest_1', 'nearest_2', 'nearest_3', 'nearest_4', 'nearest_5', 'nearest_6', 'nearest_7', 'nearest_8', 'nearest_9', 'nearest_10', 'nearest_11', 'nearest_12', 'nearest_13', 'nearest_14', 'nearest_15', 'nearest_16', 'nearest_17', 'nearest_18', 'nearest_19', 'nearest_20']

,product_id,nearest_1,nearest_2,nearest_3,nearest_4,nearest_5,nearest_6,nearest_7,nearest_8,nearest_9,...,nearest_11,nearest_12,nearest_13,nearest_14,nearest_15,nearest_16,nearest_17,nearest_18,nearest_19,nearest_20
0,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Utopia Towels Cotton Bleach Proof Salon Towels...,Healthcom Set of 5 Hair Combs Set Professional...,10 Pieces Hair Barber Styling Comb Set with 10...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Volumizing Biotin Shampoo and Conditioner Set ...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Krewey Hair Cutting Scissors Professional Home...,...,Biotin Shampoo and Conditioner Set for Hair Gr...,Hair Extension Holder and Hanger – Professiona...,Biotin Hair Thickening Spray for Thin Hair Tex...,Tube Color Storage Rack - 3 Pack,Clearform ML7889 Clear Acrylic Extra Large Tub...,Back Pain Relief Bolster Pillow - Half Moon Kn...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Hair Dye Brush Holder - Hair Color Brush Stand...
1,Utopia Towels Cotton Bleach Proof Salon Towels...,Tube Color Storage Rack - 3 Pack,Hair Dye Brush Holder - Hair Color Brush Stand...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Clearform ML7889 Clear Acrylic Extra Large Tub...,Zippity Outdoor Products ZP19018 Manchester No...,Leakproof Hidden Flask - 2 Secret Sunscreen Fl...,Backyard X-Scapes Natural Rolled Bamboo Fence ...,Bio Plas 0090 Polypropylene 96 Well Reversible...,GoPong Sneak Alcohol Anywhere Ice Flask (2 Pac...,...,"Laube Blade Case, Mini",Hallmark Shoebox Maxine All Occasions Card Ass...,"Hallmark Halloween Cards Assortment, Wicked Ca...","Hallmark Shoebox Funny Anniversary Card, Love ...","Sedona Method Course, the Vols 1-2","Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark Shoebox Funny Christmas Card (Bulldog...,Hallmark Shoebox Funny Birthday Card (Cold Beers),OSP Home Furnishings Wicker Papasan Chair with...,Hallmark Shoebox Funny Birthday Card (4 Out of...
2,Bio Plas 0090 Polypropylene 96 Well Reversible...,Tube Color Storage Rack - 3 Pack,Clearform ML7889 Clear Acrylic Extra Large Tub...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Leakproof Hidden Flask - 2 Secret Sunscreen Fl...,Hair Dye Brush Holder - Hair Color Brush Stand...,Utopia Towels Cotton Bleach Proof Salon Towels...,"Tuf-Tite Septic Tank Riser, 24''x12''",GoPong Sneak Alcohol Anywhere Ice Flask (2 Pac...,Zippity Outdoor Products ZP19018 Manchester No...,...,"Hallmark Shoebox Funny Anniversary Card, Love ...","Laube Blade Case, Mini",Hallmark Shoebox Funny Birthday Card (Cold Beers),Hallmark Shoebox Funny Birthday Card (Cupcake),Hallmark Shoebox Funny Birthday Card (4 Out of...,Hallmark Shoebox Maxine All Occasions Card Ass...,"Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark All Occasion Handmade Boxed Set of As...,Hallmark Shoebox Funny Birthday Card (A Very S...,Hallmark Shoebox Funny Christmas Card (Bulldog...
3,Tube Color Storage Rack - 3 Pack,Hair Dye Brush Holder - Hair Color Brush Stand...,Clearform ML7889 Clear Acrylic Extra Large Tub...,Bio Plas 0090 Polypropylene 96 Well Reversible...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Utopia Towels Cotton Bleach Proof Salon Towels...,GoPong Sneak Alcohol Anywhere Ice Flask (2 Pac...,Leakproof Hidden Flask - 2 Secret Sunscreen Fl...,Zippity Outdoor Products ZP19018 Manchester No...,"Tuf-Tite Septic Tank Riser, 24''x12''",...,Hallmark Shoebox Funny Christmas Cards Assortm...,Hallmark Shoebox Funny Birthday Card (4 Out of...,"Hallmark Halloween Cards Assortment, Wicked Ca...",Hallmark Shoebox Funny Birthday Card (Cold Beers),Hallmark Shoebox Funny Birthday Card (Cupcake),Hallmark Shoebox Maxine All Occasions Card Ass...,"Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark Shoebox Funny Birthday Card (A Very S...,Hallmark Shoebox Funny Christmas Card (Bulldog...,Hallmark All Occasion Handmade Boxed Set of As...
4,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Clearform ML7889 Clear Acrylic Extra Large Tub...,Hair Dye Brush Holder - Hair Color Brush Stand...,Tube Color Storage Rack - 3 Pack,Bio Plas 0090 Polypropylene 96 Well Reversible...,Utopia Towels Cotton Bleach Proof Salon Towels...,Leakproof Hidden Flask - 2 Secret Sunscreen Fl...,Zippity Outdoor Products ZP19018 Manchester No...,Backyard X-Scapes Natural Rolled Bamboo Fence ...,OSP Home Furnishings Wicker Papasan Chair with...,...,"Laube Blade Case, Mini",Hallmark Shoebox Funny Birthday Card (Cold Beers),Hallmark Shoebox Maxine All Occasions Card Ass...,GoPong Sneak Alcohol Anywhere Ice Flask (2 Pac...,"Tuf-Tite Septic Tank Riser, 24''x12''",Hallmark Shoebox Funny Christmas Cards Assortm...,"Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark Shoebox Funny Birthday Card (4 Out of...,Hallmark All Occasion Handmade Boxed Set of As...,Hallmark Shoebox Funny Birthday Card (A Very S...
5,Clearform ML7889 Clear Acrylic Extra Large Tub...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Tube Color Storage Rack - 3 Pack,Bio Plas 0090 Polypropylene 96 Well Reversible...,Hair Dye Brush Holder - Hair Color Brush Stand...,Utopia Towels Cotton Bleach Proof Salon Towels...,Backyard X-Scapes Natural Rolled Bamboo Fence ...,"Tuf-Tite Septic Tank Riser, 24''x12''",Leakproof Hidden Flask - 2 Secret Sunscreen Fl...,Zippity Outdoor Products ZP19018 Manchester No...,...,"Laube Blade Case, Mini",GoPong Sneak Alcohol Anywhere Ice Flask (2 Pac...,"Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark Birthday Card for Him (Extra Attention),Hallmark Shoebox Funny Birthday Card (Cold Beers),Hallmark All Occasion Handmade Boxed Set of As...,"Hallmark Shoebox Funny Anniversary Card, Love ...","Sedona Method Course, the Vols 1-2",Hallmark Shoebox Funny Birthday Card (Cupcake),"Hallmark Halloween Cards Assortment, Wicked Ca..."
6,"Laube Blade Case, Mini",OSP Home Furnishings Wicker Papasan Chair with...,Leakproof Hidden Flask - 2 Secret Sunscreen Fl...,Hallmark Shoebox Funny Birthday Card (A Very S...,Hallmark Shoebox Funny Birthday Card,Hair Dye Brush Holder - Hair Color Brush Stand...,Hallmark Shoebox Funny Birthday Card (Cold Beers),Hallmark Shoebox Funny Birthday Card (Cupcake),Hallmark Shoebox Funny Christmas Card (Bulldog...,GoPong Sneak Alcohol Anywhere Ice Flask (2 Pac...,...,Hallmark Shoebox Funny Birthday Card (4 Out of...,Utopia Towels Cotton Bleach Proof Salon Towels...,Hallmark Shoebox Funny Christmas Cards Assortm...,"Hallmark Shoebox Funny Anniversary Card, Love ...",Hallmark Birthday Card for Him (Extra Attention),Hallmark Shoebox Maxine All Occasions Card Ass...,Clearform ML7889 Clear Acrylic Extra Large Tub...,"Sedona Method Course, the Vols 1-2",Hallmark All Occasion Handmade Boxed Set of As...,Tube Color Storage Rack - 3 Pack
7,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Healthcom Set of 5 Hair Combs Set Professional...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,Krewey Hair Cutting Scissors Professional Home...,10 Pieces Hair Barber Styling Comb Set with 10...,Volumizing Biotin Shampoo and Conditioner Set ...,Biotin Hair Thickening Spray for Thin Hair Tex...,Biotin Shampoo and Conditioner Set for Hair Gr...,...,Hair Extension Holder and Hanger – Professiona...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,Hair Dye Brush Holder - Hair Color Brush Stand...,"Firewood Drill Bit Wood Splitter,electric log ...",Tube Color Storage Rack - 3 Pack,Utopia Towels Cotton Bleach Proof Salon Towels...,GoPong Sneak Alcohol Anywhere Ice Flask (2 Pac...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Bio Plas 0090 Polypropylene 96 Well Reversible...
8,Hair Extension Holder and Hanger – Professiona...,Krewey Hair Cutting Scissors Professional Home...,10 Pieces Hair Barber Styling Comb Set with 10...,Healthcom Set of 5 Hair Combs Set Professional...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,Biotin Hair Thickening Spray for Thin Hair Tex...,Hair Dye Brush Holder - Hair Color Brush Stand...,Boldify 3X Biotin Hair Thickening Serum - Get ...,...,Volumizing Biotin Shampoo and Conditioner Set ...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Back Pain Relief Bolster Pillow - Half Moon Kn...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,Everlasting Comfort Bolster Pillow for Legs an...,"Firewood Drill Bit Wood Splitter,electric log ...",Half Moon Bolster Semi-Roll Pillow - Ankle and...,Outry Half Face Mask - Lower Face Protective T...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Utopia Towels Cotton Bleach Proof Salon Towels...
9,Hair Dye Brush Holder - Hair Color Brush Stand...,Tube Color Storage Rack - 3 Pack,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Utopia Towels Cotton Bleach Proof Salon Towels...,Clearform ML7889 Clear Acrylic Extra Large Tub...,Bio Plas 0090 Polypropylene 96 Well Reversible...,"Hallmark Halloween Cards Assortment, Wicked Ca...",Hallmark Shoebox Maxine All Occasions Card Ass...,Hallmark All Occasion Handmade Boxed Set of As...,"Hallmark Shoebox Funny Anniversary Card, Love ...",...,"Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark Shoebox Funny Birthday Card (A Very S...,Hallmark Shoebox Funny Birthday Card (4 Out of...,"Laube Blade Case, Mini",Hallmark Shoebox Funny Birthday Card (Cupcake),Leakproof Hidden Flask - 2 Secret Sunscreen Fl...,Hallmark Birthday Card for Him (Extra Attention),Hallmark Shoebox Funny Birthday Card,Hallmark Shoebox Funny Christmas Card (Bulldog...,"Sedona Method Course , 10 CD Volume 1 + 2, plu..."
10,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,10 Pieces Hair Barber Styling Comb Set with 10...,Healthcom Set of 5 Hair Combs Set Professional...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Krewey Hair Cutting Scissors Professional Home...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,Hair Extension Holder and Hanger – Professiona...,"Firewood Drill Bit Wood Splitter,electric log ...",GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,...,Biotin Shampoo and Conditioner Set for Hair Gr...,Boldify 3X Biotin Hair Thickening Serum - Get ...,Hair Dye Brush Holder - Hair Color Brush Stand...,Volumizing Biotin Shampoo and Conditioner Set ...,100 All Occasion Greeting Cards- 100 Eye Catch...,Biotin Hair Thickening Spray for Thin Hair Tex...,"Hallmark Halloween Cards Assortment, Wicked Ca...","Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark Shoebox Funny Christmas Cards Assortm...,Leakproof Hidden Flask - 2 Secret Sunscreen Fl...
11,Healthcom Set of 5 Hair Combs Set Professional...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",10 Pieces Hair Barber Styling Comb Set with 10...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Krewey Hair Cutting Scissors Professional Home...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Hair Extension Holder and Hanger – Professiona...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,"Firewood Drill Bit Wood Splitter,electric log ...",...,Volumizing Biotin Shampoo and Conditioner Set ...,Hair Dye Brush Holder - Hair Color Brush Stand...,Biotin Hair Thickening Spray for Thin Hair Tex...,Boldify 3X Biotin Hair Thickening Serum - Get ...,Outry Half Face Mask - Lower Face Protective T...,100 All Occasion Greeting Cards- 100 Eye Catch...,Back Pain Relief Bolster Pillow - Half Moon Kn...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Utopia Towels Cotton Bleach Proof Salon Towels...,Cushy Form Bolster Pillow for Lumbar and Leg S...
12,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Healthcom Set of 5 Hair Combs Set Professional...,10 Pieces Hair Barber Styling Comb Set with 10...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Krewey Hair Cutting Scissors Professional Home...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,Hair Extension Holder and Hanger – Professiona...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,Volumizing Biotin Shampoo and Conditioner Set ...,...,"Firewood Drill Bit Wood Splitter,electric log ...",Biotin Hair Thickening Spray for Thin Hair Tex...,Boldify 3X Biotin Hair Thickening Serum - Get ...,Hair Dye Brush Holder - Hair Color Brush Stand...,Back Pain Relief Bolster Pillow - Half Moon Kn...,Half Moon Bolster Semi-Roll Pillow - Ankle and...,100 All Occasion Greeting Cards- 100 Eye Catch...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Outry Half Face Mask - Lower Face Protective T...,Cushy Form Bolster Pillow for Lumbar and Leg S...
13,10 Pieces Hair Barber Styling Comb Set with 10...,Healthcom Set of 5 Hair Combs Set Professional...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Krewey Hair Cutting Scissors Professional Home...,Hair Extension Holder and Hanger – Professiona...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,"Firewood Drill Bit Wood Splitter,electric log ...",YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,...,100 All Occasion Greeting Cards- 100 Eye Catch...,Biotin Shampoo and Conditioner Set for Hair Gr...,Hair Dye Brush Holder - Hair Color Brush Stand...,Volumizing Biotin Shampoo and Conditioner Set ...,Biotin Hair Thickening Spray for Thin Hair Tex...,Half Moon Bolster Semi-Roll Pillow - Ankle and...,"Hallmark Halloween Cards Assortment, Wicked Ca...",Pana Black 6 Tier Large Wall Mounted Metal Rac...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Boldify 3X Biotin Hair Thickening Serum - Get ...
14,Krewey Hair Cutting Scissors Professional Home...,Healthcom Set of 5 Hair Combs Set Professional...,Hair Extension Holder and Hanger – Professiona...,10 Pieces Hair Barber Styling Comb Set with 10...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Biotin Shampoo and Conditioner Set for Hair Gr...,"Firewood Drill Bit Wood Splitter,electric log ...",...,Boldify 3X Biotin Hair Thickening Serum - Get ...,Volumizing Biotin Shampoo and Conditioner Set ...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,Outry Half Face Mask - Lower Face Protective T...,"Laube Blade Case, Mini",Hair Dye Brush Holder - Hair Color Brush Stand...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Back Pain Relief Bolster Pillow - Half Moon Kn...,How to Quickly Use the Sedona Method KISS Rele...,The Sedona Method Course Workbook: Your Key to...
15,"Firewood Drill Bit Wood Splitter,electric log ...",10 Pieces Hair Barber Styling Comb Set with 10...,Healthcom Set of 5 Hair Combs Set Professional...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Krewey Hair Cutting Scissors Professional Home...,Outry Half Face Mask - Lower Face Protective T...,Hair Extension Holder and Hanger – Professiona...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,...,Half Moon Bolster Semi-Roll Pillow - Ankle and...,Hair Dye Brush Holder - Hair Color Brush Stand...,Back Pain Relief Bolster Pillow - Half Moon Kn...,Backyard X-Scapes Natural Rolled Bamboo Fence ...,"Hallmark Halloween Cards Assortment, Wicked Ca...",Hallmark Shoebox Funny Christmas Cards Assortm...,"Sedona Method Course , 10 CD Volume 1 + 2, plu...","Hallmark Shoebox Funny Boxed Christmas Cards, ...",Hallmark All Occasion Handmade Boxed Set of As...,"Laube Blade Case, Mini"
16,Boldify 3X Biotin Hair Thickening Serum - Get ...,Biotin Hair Thickening Spray for Thin Hair Tex...,Biotin Shampoo and Conditioner Set for Hair Gr...,Volumizing Biotin Shampoo and Conditioner Set ...,Hair Extension Holder and Hanger – Professiona...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Krewey Hair Cutting Scissors Professional Home...,Back Pain Relief Bolster Pillow - Half Moon Kn...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,Everlasting Comfort Bolster Pillow for Legs an...,10 Pieces Hair Barber Styling Comb Set with 10...,Half Moon Bolster Semi-Roll Pillow - Ankle and...,Hair Dye Brush Holder - Hair Color Brush Stand...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Bio Plas 0090 Polypropylene 96 Well Reversible...,Cushy Form Bolster Pillow for Lumbar and Leg S...,"Sedona Method Course , 10 CD Volume 1 + 2, plu..."
17,Volumizing Biotin Shampoo and Conditioner Set ...,Biotin Shampoo and Conditioner Set for Hair Gr...,Biotin Hair Thickening Spray for Thin Hair Tex...,Boldify 3X Biotin Hair Thickening Serum - Get ...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Healthcom Set of 5 Hair Combs Set Professional...,Hair Extension Holder and Hanger – Professiona...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,Krewey Hair Cutting Scissors Professional Home...,...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,10 Pieces Hair Barber Styling Comb Set with 10...,Everlasting Comfort Bolster Pillow for Legs an...,Half Moon Bolster Semi-Roll Pillow - Ankle and...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Hair Dye Brush Holder - Hair Color Brush Stand...,Bio Plas 0090 Polypropylene 96 Well Reversible...,Leakproof Hidden Flask - 2 Secret Sunscreen Fl...
18,Biotin Shampoo and Conditioner Set for Hair Gr...,Biotin Hair Thickening Spray for Thin Hair Tex...,Volumizing Biotin Shampoo and Conditioner Set ...,Boldify 3X Biotin Hair Thickening Serum - Get ...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Healthcom Set of 5 Hair Combs Set Professional...,Hair Extension Holder and Hanger – Professiona...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,Krewey Hair Cutting Scissors Professional Home...,Back Pain Relief Bolster Pillow - Half Moon Kn...,...,10 Pieces Hair Barber Styling Comb Set with 10...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Binocktails Bev-Brush Paddle Hairbrush Secret ...,Everlasting Comfort Bolster Pillow for Legs an...,Hair Dye Brush Holder - Hair Color Brush Stand...,Bio Plas 0090 Polypropylene 96 Well Reversible...,Half Moon Bolster Semi-Roll Pillow - Ankle and...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Utopia Towels Cotton Bleach Proof Salon Towels...
19,Biotin Hair Thickening Spray for Thin Hair Tex...,Biotin Shampoo and Conditioner Set for Hair Gr...,Boldify 3X Biotin Hair Thickening Serum - Get ...,Volumizing Biotin Shampoo and Conditioner Set ...,Hair Extension Holder and Hanger – Professiona...,YJYdada 1PC Mixing Paint Stirrer Pro Salon Hai...,"20 Pieces Hair Dye Brush and Bowl Set, Hair Dy...",Krewey Hair Cutting Scissors Professional Home...,Healthcom Set of 5 Hair Combs Set Professional...,GREEN LIFESTYLE Black Bleach Proof Towels Bulk...,...,10 Pieces Hair Barber Styling Comb Set with 10...,Back Pain Relief Bolster Pillow - Half Moon Kn...,6 Pieces Rat Tail Comb Fiber Teasing Combs Rat...,Everlasting Comfort Bolster Pillow for Legs an...,Bio Plas 0090 Polypropylene 96 Well Reversible...,Hair Dye Brush Holder - Hair Color Brush Stand...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Cushy Form Bolster Pillow for Lumbar and Leg S...,Pana Black 6 Tier Large Wall Mounted Metal Rac...,Utopia Towels Cotton Bleach Proof Salon Towels...